const defultLeads = [
  {
    id: "L-101",
    name: "Aarav Mehta",
    company: "Reliance Industries",
    email: "aarav.mehta@reliance.com",
    phone: "+91 98765 43210",
    source: "LinkedIn",
    status: "New",
    owner: "Siddharth Patel",
    estimatedValue: 150000,
    createdAt: "2026-05-10"
  },
  {
    id: "L-102",
    name: "Priya Sharma",
    company: "Tata Consultancy Services",
    email: "priya.sharma@tcs.com",
    phone: "+91 91234 56789",
    source: "Website Form",
    status: "Contacted",
    owner: "Anjali Rao",
    estimatedValue: 85000,
    createdAt: "2026-05-12"
  },
  {
    id: "L-103",
    name: "Vikram Malhotra",
    company: "Infosys Ltd",
    email: "v.malhotra@infosys.in",
    phone: "+91 99887 76655",
    source: "Cold Call",
    status: "Qualified",
    owner: "Siddharth Patel",
    estimatedValue: 320000,
    createdAt: "2026-05-14"
  },
  {
    id: "L-104",
    name: "Sneha Desai",
    company: "Adani Group",
    email: "sneha.desai@adani.com",
    phone: "+91 94260 11223",
    source: "Referral",
    status: "Converted",
    owner: "Anjali Rao",
    estimatedValue: 45000,
    createdAt: "2026-05-15"
  },
  {
    id: "L-105",
    name: "Rohan Joshi",
    company: "Wipro Technologies",
    email: "rohan.joshi@wipro.com",
    phone: "+91 95555 44321",
    source: "LinkedIn",
    status: "Lost",
    owner: "Amit Shah",
    estimatedValue: 0,
    createdAt: "2026-05-16"
  },
  {
    id: "L-106",
    name: "Deepak Verma",
    company: "HDFC Bank",
    email: "deepak.verma@hdfc.com",
    phone: "+91 98123 45670",
    source: "Website Form",
    status: "New",
    owner: "Siddharth Patel",
    estimatedValue: 210000,
    createdAt: "2026-05-17"
  },
  {
    id: "L-107",
    name: "Ananya Iyer",
    company: "Zomato",
    email: "ananya.i@zomato.media",
    phone: "+91 93456 78901",
    source: "LinkedIn",
    status: "Qualified",
    owner: "Amit Shah",
    estimatedValue: 125000,
    createdAt: "2026-05-17"
  },
  {
    id: "L-108",
    name: "Rajesh Patel",
    company: "Flipkart",
    email: "rajesh.patel@flipkart.com",
    phone: "+91 98250 99887",
    source: "Cold Call",
    status: "Contacted",
    owner: "Siddharth Patel",
    estimatedValue: 95000,
    createdAt: "2026-05-01"
  },
  {
    id: "L-109",
    name: "Kiran Nair",
    company: "Paytm",
    email: "kiran.nair@paytm.com",
    phone: "+91 97441 22334",
    source: "Website Form",
    status: "New",
    owner: "Anjali Rao",
    estimatedValue: 60000,
    createdAt: "2026-05-02"
  },
  {
    id: "L-110",
    name: "Divya Teja",
    company: "Ola Cabs",
    email: "divya.teja@ola.in",
    phone: "+91 96332 55441",
    source: "LinkedIn",
    status: "Qualified",
    owner: "Amit Shah",
    estimatedValue: 180000,
    createdAt: "2026-05-03"
  },
  {
    id: "L-111",
    name: "Arjun Reddy",
    company: "Swiggy",
    email: "arjun.reddy@swiggy.in",
    phone: "+91 95221 66778",
    source: "Referral",
    status: "Converted",
    owner: "Siddharth Patel",
    estimatedValue: 110000,
    createdAt: "2026-05-04"
  },
  {
    id: "L-112",
    name: "Manish Gupta",
    company: "Byju's",
    email: "manish.gupta@byjus.com",
    phone: "+91 94112 88990",
    source: "Cold Call",
    status: "Lost",
    owner: "Anjali Rao",
    estimatedValue: 0,
    createdAt: "2026-05-05"
  },
  {
    id: "L-113",
    name: "Pooja Hegde",
    company: "Nykaa",
    email: "pooja.hegde@nykaa.com",
    phone: "+91 93001 44556",
    source: "Website Form",
    status: "New",
    owner: "Amit Shah",
    estimatedValue: 75000,
    createdAt: "2026-05-06"
  },
  {
    id: "L-114",
    name: "Sanjay Dutt",
    company: "Tech Mahindra",
    email: "sanjay.dutt@techm.com",
    phone: "+91 92998 11223",
    source: "LinkedIn",
    status: "Contacted",
    owner: "Siddharth Patel",
    estimatedValue: 230000,
    createdAt: "2026-05-07"
  },
  {
    id: "L-115",
    name: "Harish Kumar",
    company: "L&T Infotech",
    email: "harish.k@lnt.com",
    phone: "+91 91887 33445",
    source: "Referral",
    status: "Qualified",
    owner: "Anjali Rao",
    estimatedValue: 140000,
    createdAt: "2026-05-08"
  },
  {
    id: "L-116",
    name: "Megha Rao",
    company: "ICICI Bank",
    email: "megha.rao@icici.com",
    phone: "+91 90776 55667",
    source: "Website Form",
    status: "New",
    owner: "Amit Shah",
    estimatedValue: 310000,
    createdAt: "2026-05-09"
  },
  {
    id: "L-117",
    name: "Nitin Saxena",
    company: "Maruti Suzuki",
    email: "nitin.s@maruti.co.in",
    phone: "+91 99665 77889",
    source: "LinkedIn",
    status: "Contacted",
    owner: "Siddharth Patel",
    estimatedValue: 50000,
    createdAt: "2026-05-10"
  },
  {
    id: "L-118",
    name: "Swati Mishra",
    company: "Airtel India",
    email: "swati.m@airtel.com",
    phone: "+91 98554 99001",
    source: "Cold Call",
    status: "Converted",
    owner: "Anjali Rao",
    estimatedValue: 90000,
    createdAt: "2026-05-11"
  },
  {
    id: "L-119",
    name: "Abhishek Singh",
    company: "Mahindra & Mahindra",
    email: "abhishek.s@mahindra.com",
    phone: "+91 97443 11223",
    source: "Referral",
    status: "Qualified",
    owner: "Amit Shah",
    estimatedValue: 270000,
    createdAt: "2026-05-12"
  },
  {
    id: "L-120",
    name: "Kavita Chawla",
    company: "Biocon",
    email: "kavita.c@biocon.com",
    phone: "+91 96332 44556",
    source: "Website Form",
    status: "Lost",
    owner: "Siddharth Patel",
    estimatedValue: 0,
    createdAt: "2026-05-13"
  },
  {
    id: "L-121",
    name: "Rahul Dravid",
    company: "BCCI Tech",
    email: "rahul.d@bcci.tv",
    phone: "+91 95221 88990",
    source: "LinkedIn",
    status: "New",
    owner: "Anjali Rao",
    estimatedValue: 400000,
    createdAt: "2026-05-14"
  },
  {
    id: "L-122",
    name: "Neha Kakkar",
    company: "T-Series Labs",
    email: "neha.k@tseries.com",
    phone: "+91 94110 33445",
    source: "Cold Call",
    status: "Contacted",
    owner: "Amit Shah",
    estimatedValue: 120000,
    createdAt: "2026-05-15"
  },
  {
    id: "L-123",
    name: "Sachin Tendulkar",
    company: "SRT Sports",
    email: "sachin@srt.com",
    phone: "+91 93009 77889",
    source: "Referral",
    status: "Qualified",
    owner: "Siddharth Patel",
    estimatedValue: 500000,
    createdAt: "2026-05-16"
  },
  {
    id: "L-124",
    name: "Gaurav Taneja",
    company: "Air India",
    email: "gaurav.t@airindia.com",
    phone: "+91 92996 55667",
    source: "Website Form",
    status: "Converted",
    owner: "Anjali Rao",
    estimatedValue: 35000,
    createdAt: "2026-05-17"
  },
  {
    id: "L-125",
    name: "Shreya Ghoshal",
    company: "Sony Music India",
    email: "shreya.g@sony.com",
    phone: "+91 91885 11223",
    source: "LinkedIn",
    status: "New",
    owner: "Amit Shah",
    estimatedValue: 165000,
    createdAt: "2026-05-18"
  }
];

const savedData = localStorage.getItem('salesflow_leads');
export const mockLeads = savedData ? JSON.parse(savedData) : defultLeads; 